Adt 434 support test environment timeout argument
jenkinsci/eggplant-runner-plugin pull request #45
Opened 2022-11-14 06:56 UTC by curveenk

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ x Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-11-14 11:33 UTC, poasungoh requested changes

2022-11-14 11:33 UTC, poasungoh commented on src/test/java/io/jenkins/plugins/eggplant/EggplantRunnerBuilderTest.java
> +
Can we add some test scope for below cases:
 - Decimal value
 - +- value
 - empty value
 - Alpha+numeric : 5a

2022-11-15 02:32 UTC, curveenk commented on src/test/java/io/jenkins/plugins/eggplant/EggplantRunnerBuilderTest.java
> +
unit test added

2022-11-15 07:30 UTC, poasungoh approved these changes

2022-11-15 07:32 UTC, merged